server:
    port: 9500
eureka:
    instance:
        hostname: register # eureka实例的主机名
    client:
        register-with-eureka: false #不把自己注册到eureka上
        fetch-registry: false #不从eureka上来获取服务的注册信息
        service-url:
            defaultZone: http://39.106.62.195:9500/eureka/